# First Tutorial

In [1]:
list1 = [1.2, 2.3]
print (list1)
list2 = [1,2]
print (list1 + list2)
list3 = list1 + list2
print(list3)

[1.2, 2.3]
[1.2, 2.3, 1, 2]
[1.2, 2.3, 1, 2]


In [2]:
import numpy as np
arr = np.arange(1000000)

In [3]:
pythlist = list(range(1000000))

In [4]:
%time for _ in range(10): [item*3 for item in pythlist]

CPU times: user 501 ms, sys: 175 ms, total: 676 ms
Wall time: 676 ms


In [5]:
%time for _ in range(10): arr = arr*3

CPU times: user 12.2 ms, sys: 7.27 ms, total: 19.5 ms
Wall time: 19.5 ms


In [6]:
a = np.array([2,3,4,5,6])
print (a)
type(a)

[2 3 4 5 6]


numpy.ndarray

In [7]:
a

array([2, 3, 4, 5, 6])

In [8]:
a=a+1

In [9]:
a

array([3, 4, 5, 6, 7])

In [10]:
print (a)

[3 4 5 6 7]


In [19]:
d2 = np.array([[1,2,3,4], [5,6,7,8]])
print(d2+2)
d2.shape
d2.dtype

[[ 3  4  5  6]
 [ 7  8  9 10]]


dtype('int64')

In [12]:
d3 = np.array([[1,2,3,4], [5,6,7,8.6]], dtype= 'int32')
print(d3)
d3.dtype

[[1 2 3 4]
 [5 6 7 8]]


dtype('int32')

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
a= np.zeros((4,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
one = np.ones(4)
print(one)
one.dtype

[1. 1. 1. 1.]


dtype('float64')

In [16]:
np.empty((4,6)) #not necessarily zeroes: can assign garbage values

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
d3**d3 #To the power same number 7^7

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)